stages:

  process:
    cmd: python stages/01_load.py
    deps:
    - stages/01_load.py
    - downloads/MIE_multitask_model_data_20230601.xlsx
    - downloads/endpoint_names.xlsx
    outs:
    - brick/bayer_dili_data.parquet
    - brick/bayer_dili_properties.parquet
